### ISSUE TITLE
Header is empty in Chrome 41.0.2272.118 (Official Build) / Linux Mint 17

### ISSUE THREAD

**Issue by pietro909** [filearts/plunker_www#61]
Hi there,
I found this problem using Plunker with Chrome:

![plunker_issue](https://cloud.githubusercontent.com/assets/2094604/7084194/e1536ada-df6a-11e4-8ec3-09ca245b85cc.jpg)

The element 
```html
<nav class="navbar navbar-fixed-top">
```

containing buttons is not showing: this is due to the behavior of the css fixed positioning:

```css
.navbar-fixed-top, .navbar-fixed-bottom {
  position: fixed;
  right: 0;
  left: 0;
  z-index: 1030;
  margin-bottom: 0;
}
```

I will dig a little bit more in order to fix it, in the meanwhile can someone confirm similar issue in Chrome for Windows / OSX or Safari?

thank you guys,
Pietro
